apiVersion: v1
kind: Service
metadata:
  annotations:
  labels: {{- include "standardLabels"  . | nindent 4 }}
    app.kubernetes.io/component:  {{ .Release.Name }}-front
    io.lago.service: {{ .Release.Name }}-front
  name: {{ .Release.Name}}-front-svc
spec:
  ports:
    - name: "front"
      port: {{ .Values.front.service.port }}
      targetPort: 80
  selector:
    io.lago.service: {{ .Release.Name }}-front
