apiVersion: v1
kind: Service
metadata:
  annotations:
  labels: {{- include "standardLabels"  . | nindent 4 }}
    app.kubernetes.io/component:  {{ .Release.Name }}-pdf
    io.lago.service: {{ .Release.Name }}-pdf
  name: {{ .Release.Name}}-pdf-svc
spec:
  ports:
    - name: "pdf"
      port: {{ .Values.pdf.service.port }}
      targetPort: 3000
  selector:
    io.lago.service: {{ .Release.Name }}-pdf
