{{- if not .Values.global.s3.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {{- include "standardLabels"  . | nindent 4 }}
    app.kubernetes.io/component:  {{ .Release.Name }}-storage-data
    io.lago.service: {{ .Release.Name }}-storage-data
  name: {{ .Release.Name }}-storage-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.api.volumes.storage }}
{{- end -}}
